services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mydb:
    image: postgres
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - vipvol:/var/lib/postgresql/data

  front:
    image: lalyos/lunch:v8
    # build: .
    ports:
      - 80
    environment:
      - VIRTUAL_HOST=lunch.vcap.me
      - TITLE=LunchBreak
      - COLOR=lightgreen

  coffe:
    build: .
    ports:
      - 80
    environment:
      - VIRTUAL_HOST=coffe.vcap.me
      - TITLE=CoffeBreak
      - COLOR=tan

volumes:
  vipvol: