version: '3.9'
services:
  wed:
    image: lalyos/lunch:v8
    environment:
      - TITLE=${TITLE:-default}
      - COLOR=${COLOR:-lightgray}
    ports:
      - 30002:80
    deploy:
      replicas: 1
      