version: '3.9'
services:
  coffee:
    image: lalyos/lunch:v10
    ports:
      - 30004:80
    environment:
    - TITLE_FILE=/title
    - COLOR_FILE=/color
    - BODY_FILE=/body
    configs:
    - source: title
      target: /title
    - source: color
      target: /color
    - source: body
      target: /body
    deploy:
      labels:
        traefik.port: 80

configs:
  body: 
    external: true
    name: ${ENV:-qa}-body
  color:
    external: true
    name: ${ENV:-qa}-color
  title: 
    external: true
    name: ${ENV:-qa}-title

networks:
  default:
    external: true
    name: operation_default